In [21]:
import torch
import torch.nn as nn

x = torch.tensor([[10, 11, 12, 13, 14]], dtype=torch.float32).unsqueeze(-1)
y = torch.tensor([[15, 16, 17, 18, 19]], dtype=torch.float32).unsqueeze(-1)



In [22]:
rnn = nn.RNN(input_size=1, hidden_size=5, batch_first=True)
linear = nn.Linear(in_features=5, out_features=1)
out, h = rnn(x)
print(out)
print(h)
y_pred = linear(out)
print(y_pred.shape)

tensor([[[ 0.7522, -0.9397,  0.9998,  0.9977, -0.9926],
         [ 0.7660, -0.9517,  1.0000,  0.9986, -0.9905],
         [ 0.8200, -0.9656,  1.0000,  0.9992, -0.9943],
         [ 0.8645, -0.9755,  1.0000,  0.9996, -0.9965],
         [ 0.8983, -0.9826,  1.0000,  0.9998, -0.9979]]],
       grad_fn=<TransposeBackward1>)
tensor([[[ 0.8983, -0.9826,  1.0000,  0.9998, -0.9979]]],
       grad_fn=<StackBackward0>)
torch.Size([1, 5, 1])


In [24]:
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(list(rnn.parameters()) + list(linear.parameters()), lr=0.001)

for epoch in range(1000):
    optimizer.zero_grad()
    out, h = rnn(x)
    y_pred = linear(out)
    loss = criterion(y_pred, y)
    loss.backward()
    optimizer.step()

out, h= rnn(x)
y_pred = linear(out)
print(y_pred)

tensor([[[15.0014],
         [16.0040],
         [17.0023],
         [18.0103],
         [18.9943]]], grad_fn=<ViewBackward0>)
